### ISSUE TITLE
textures 

### ISSUE THREAD

**Issue by xBeSx** [JarateKing/CleanTF2plus#16]
Was working fine but then in a game with sv_pure 2 this happened:

![image](https://user-images.githubusercontent.com/87492460/125826178-c0d7952f-19be-4c6a-a105-cb4a72873bd7.png)

Is it normal?

**Comment by micwoj92** [comment]
Yes, this is normal and not a bug. Should be closed.

W dniu czwartek, 15 lipca 2021 xBeSx ***@***.***> napisał(a):

**Comment by xBeSx** [comment]
wut is it really normal? It wasn't like this the game before
