### ISSUE TITLE
Unable to run generate.sh

### ISSUE THREAD

**Issue by zpcv** [JarateKing/CleanTF2plus#2]
When I try to run generate.sh on Ubuntu 19.04 Disco I get the following error:

`generate.sh: line 3: dev/generators/textures_flat.sh: Permission denied`
`generate.sh: line 5: dev/generators/models_null.sh: Permission denied`

**Comment by JarateKing** [comment]
That was my bad, I've done something that I think should fix it (or at least move on to a new error).

**Comment by zpcv** [comment]
Thank you, it works now. Closing the issue
