### ISSUE TITLE
unexpected operator error when selecting any option in the .sh file

### ISSUE THREAD

**Issue by Bread1009** [JarateKing/CleanTF2plus#26]
i run linux (ubuntu) and when i saw this i thought i would give it a try. put it in the specified file path but when it asks the Y/N questions, no matter what i put it just gives the error above.

what i get:

./generate.sh 
would you like flat materials? Y/N/HELP
Y
./generate.sh: 217: [: Y: unexpected operator
./generate.sh: 220: [: Y: unexpected operator
./generate.sh: 222: [: Y: unexpected operator
invalid input
would you like flat materials? Y/N/HELP

please help, thanks!

**Comment by Pyogenics** [comment]
What linux distribution and shell are you using?

**Comment by Pyogenics** [comment]
A potential fix maybe to change the first line from `#!/bin/sh` to `#!/bin/bash`, since ubuntu seems to use a different shell for sh instead of bash?

**Comment by Bread1009** [comment]
looks like switching the sh to bash worked! thank you!

**Comment by Pyogenics** [comment]
I will create a PR an replace this in the code to prevent future issues, thanks for exposing this issue.

**Comment by Bread1009** [comment]
No problem.
