### ISSUE TITLE
./generate.sh uses too much memory

### ISSUE THREAD

**Issue by pasimko** [JarateKing/CleanTF2plus#3]
Running generate.sh will begin the process of creating textures. (Not sure if there's supposed to be a prompt that waits for input, but there isn't)

This process will continue for several minutes running normally until all RAM has been used and the system crashes.

System specs: 
Manjaro Linux x86_64
Kernel: 4.16.18-rt12-MANJARO
CPU: i5-6500 3.6 GHz
GPU: RX 580 8GB
RAM: 16GB

ImageMagick: 7.0.8-59 Q16 x86_64 2019-08-04
wine-4.13

**Comment by JarateKing** [comment]
Prompt isn't set up for the .sh version, it's still very WIP.

I will have to investigate, since it shouldn't be leaking memory like that (for reference, when I run it on the linux computer I use to develop the .sh version, it takes up at most ~20 MB of my 4GB ram computer).

What error messages are you getting as the script is running? And for the vtf files that do generate, what do they end up looking like?

**Comment by pasimko** [comment]
Here's the terminal output before pressing ctrl+c
```
THIS IS A WIP
THIS CURRENTLY ONLY DOES:
- FLAT TEXTURES
- NOHATS
Processing materials/brick/brickwall001b_height-ssbump.vtf...
 Information:
  Version: v7.3
  Size On Disk: 682.91 KB
  Width: 1024
  Height: 1024
  Depth: 1
  Frames: 1
  Start Frame: 0
  Faces: 1
  Mipmaps: 11
  Flags: 0x08000000
  Bumpmap Scale: 1.00
  Reflectivity: 0.21, 0.22, 0.21
  Format: DXT1

  Resources: 4
 Creating texture:
  Writing materials/brick/brickwall001b_height-ssbump.tga...
  materials/brick/brickwall001b_height-ssbump.tga written.

materials/brick/brickwall001b_height-ssbump.vtf processed.

1/1 files completed.
002c:fixme:msvcrt:__clean_type_info_names_internal (0x609b38) stub
Processing materials/brick/brickwall001b.vtf...
 Information:
  Version: v7.3
  Size On Disk: 682.91 KB
  Width: 1024
  Height: 1024
  Depth: 1
  Frames: 1
  Start Frame: 0
  Faces: 1
  Mipmaps: 11
  Flags: 0x00000040
  Bumpmap Scale: 1.00
  Reflectivity: 0.19, 0.11, 0.09
  Format: DXT1

  Resources: 4
 Creating texture:
  Writing materials/brick/brickwall001b.tga...
  materials/brick/brickwall001b.tga written.

materials/brick/brickwall001b.vtf processed.


```
Here's the image output of the tga files:
https://i.imgur.com/S0ikAlw.png

I can't open the .vtf files, but the sha256 sum of brickwall001b.vtf is `caf8461b68cb2ef3ff1bbe0f29706ffc504d4693d9b1792285492e09676e2106`
