### ISSUE TITLE
A hat not showing up when i only selected flat textures. 

### ISSUE THREAD

**Issue by thatonefaker** [JarateKing/CleanTF2plus#4]
I only selected not resized flat textures and a hat didn't show up in-game, but it did show up in the loadout menu. It was the Ghastlierest Gibus and its variations. If you need screenshots i can send them.  I didn't select remove hats or anything, just non-resized flat textures.

**Comment by thatonefaker** [comment]
Problem was fixed for some reason after a few restarts. My aplogies.

**Comment by JarateKing** [comment]
No worries, if something like this happens again then you should be able to delete the `models` folder from the generated folders
